language: minimal

sudo: required

services:
  - docker

dist: trusty

notifications:
  email: false

env:
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

before_install: docker build -t sklearn-porter .

before_script: >
  docker run -t sklearn-porter &&
    gcc --version &&
    java -version &&
    node --version &&
    go version &&
    php --version &&
    ruby --version &&
    python --version

script: >
  docker run -t sklearn-porter
    conda run -n sklearn-porter
      pytest tests -v -x -p no:doctest
        -o python_files="*Test.py"
        -o python_functions="test_*"
