language: minimal

sudo: required

services:
  - docker

dist: trusty

git:
  depth: 3

notifications:
  email: false

env:
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

before_install:
  docker build
    -t sklearn-porter
    --build-arg PYTHON_VERSION=${PYTHON_VERSION}
    --no-cache .

before_script:
  - docker run -d -t --name test sklearn-porter
  - docker exec -it test gcc --version
  - docker exec -it test java -version
  - docker exec -it test node --version
  - docker exec -it test go version
  - docker exec -it test php --version
  - docker exec -it test ruby --version
  - docker exec -it test python --version
  - docker exec -it test conda run -n sklearn-porter python --version

script:
  docker exec -it test
    conda run -n sklearn-porter
      pytest tests -v -x -p no:doctest
        -o python_files="*Test.py"
        -o python_functions="test_*"

after_script: docker rm -f $(docker ps --filter name=test -q)
